config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
  	resources :customization_options

  	resources :products do
      resources :product_customization_options do
        collection do
          post :update_positions
        end
        
    		resources :product_customization_option_values do
    			collection do
    				post :update_positions
    			end
    		end
      end
    end
  end
end

app/models/spree/customization_option.rb
module Spree
	class CustomizationOption < Spree::Base
		# has_and_belongs_to_many :prototypes, join_table: 'spree_customization_options_prototypes'

    has_many :product_customization_options, dependent: :delete_all, inverse_of: :customization_option
    has_many :products, through: :product_customization_options

    validates :name, :presentation, presence: true

    scope :sorted, -> { order(:name) }

    after_touch :touch_all_products

    self.whitelisted_ransackable_attributes = ['presentation']

    private

    def touch_all_products
      products.update_all(updated_at: Time.current)
    end
	end
end

app/models/spree/product_customization_option.rb
module Spree
	class ProductCustomizationOption < Spree::Base
		acts_as_list scope: :product

		belongs_to :product, class_name: 'Spree::Product', inverse_of: :product_customization_options
		belongs_to :customization_option, class_name: 'Spree::CustomizationOption', inverse_of: :product_customization_options

		has_many :product_customization_option_values
		accepts_nested_attributes_for :product_customization_option_values, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

    validates :customization_option, :product, :name, presence: true

    validates_with Spree::Validations::DbMaximumLengthValidator, field: :name

    default_scope { order("#{self.table_name}.position") }
    # scope :sorted, -> { order(:name) }

    self.whitelisted_ransackable_attributes = ['name']

    after_touch :touch_all_products

    # virtual attributes for use with AJAX completion stuff
    def customization_option_name
      customization_option.name if customization_option
    end

    def customization_option_name=(name)
      unless name.blank?
        unless customization_option = CustomizationOption.find_by(name: name)
          customization_option = CustomizationOption.create(name: name, presentation: name)
        end
        self.customization_option = customization_option
      end
    end

    private

    def touch_all_products
      product.update(updated_at: Time.current)
    end


	end
end

app/models/spree/product_customization_option_value.rb
module Spree
	class ProductCustomizationOptionValue < Spree::Base
		acts_as_list scope: :product_customization_option

    belongs_to :product_customization_option, dependent: :delete, inverse_of: :product_customization_option_values
    has_one :product, through: :product_customization_options

    validates :name, :presentation, presence: true

    scope :sorted, -> { order(:name) }

    after_touch :touch_product_customization_options

    self.whitelisted_ransackable_attributes = ['presentation']

    private

    def touch_product_customization_options
      product_customization_option.update(updated_at: Time.current)
    end
	end
end

app/controllers/spree/admin/customization_options_controller.rb
module Spree
  module Admin
    class CustomizationOptionsController < ResourceController
      def index
        respond_with(@collection)
      end

      private

      def collection
        return @collection if @collection.present?
        # params[:q] can be blank upon pagination
        params[:q] = {} if params[:q].blank?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
              page(params[:page]).
              per(Spree::Config[:properties_per_page])

        @collection
      end
    end
  end
end

app/controllers/spree/admin/product_customization_option_values_controller.rb
module Spree
  module Admin
    class ProductCustomizationOptionValuesController < ResourceController
      belongs_to 'spree/admin/product_customization_option', :find_by => :id
  
    end
  end
end

app/controllers/spree/admin/product_customization_options_controller.rb
module Spree
  module Admin
    class ProductCustomizationOptionsController < ResourceController
      belongs_to 'spree/product', :find_by => :slug
      before_action :find_customization_options
      before_action :setup_customization_option, only: :index

      def edit
         # = ProductCustomizationOption.find(params[:id])
        if @product_customization_option.product_customization_option_values.blank?
          @product_customization_option.product_customization_option_values.build
        end
      end

      private
        def find_customization_options
          @customization_options = Spree::CustomizationOption.pluck(:name)
        end

        def setup_customization_option
          @product.product_customization_options.build
        end
    end
  end
end

app/views/spree/admin/customization_options/_form.html.erb
<div data-hook="admin_customization_option_form" class="row">
  <div class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= f.field_container :presentation, class: ['form-group'] do %>
      <%= f.label :presentation, Spree.t(:presentation) %> <span class="required">*</span>
      <%= f.text_field :presentation, :class => 'form-control' %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
</div>

app/views/spree/admin/customization_options/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::CustomizationOption.model_name.human) %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @customization_option } %>

<%= form_for [:admin, @customization_option] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/customization_options/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::CustomizationOption) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_customization_option), new_object_url, { :class => "btn-success", :icon => 'add', 'data-update' => 'new_customization_option', :id => 'new_customization_option_link' } %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_customization_option_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>

      <%- locals = {:f => f} %>

      <div class="row">
        <div class="col col-md-6">
          <div data-hook="admin_property_index_search" class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, :class => "form-control js-quick-search-target" %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :presentation_cont, Spree.t(:presentation) %>
            <%= f.text_field :presentation_cont, :class => "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-actions" data-hook="admin_customization_options_index_search_buttons">
        <%= button Spree.t(:search), 'search' %>
      </div>

    <% end %>
  </div>
<% end %>

<% if @customization_options.any? %>
  <table class="table" id='listing_customization_options' data-hook>
    <thead>
      <tr data-hook="listing_customization_options_header">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:presentation) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @customization_options.each do |customization_option| %>
        <tr id="<%= spree_dom_id customization_option %>" data-hook="listing_customization_options_row">
          <td><%= customization_option.name %></td>
          <td><%= customization_option.presentation %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit(customization_option, :no_text => true) %>
            <%= link_to_delete(customization_option, :no_text => true) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::CustomizationOption)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= paginate @collection %>

app/views/spree/admin/customization_options/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @customization_option } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_customization_option) %>
<% end %>

<%= form_for [:admin, @customization_option] do |f| %>
  <fieldset data-hook="new_property">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-actions">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/product_customization_options/_form.html.erb
<div data-hook="admin_customization_option_form" class="row">
  <div class="col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= f.field_container :presentation, class: ['form-group'] do %>
      <%= f.label :presentation, Spree.t(:presentation) %> <span class="required">*</span>
      <%= f.text_field :presentation, :class => 'form-control' %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
</div>

app/views/spree/admin/product_customization_options/_message_customization_values.html.erb
<tr class="product_customization_option_value fields" id="spree_<%= dom_id(f.object) %>" data-hook="product_customization_option_value">

  <td class="move-handle">
    <% if f.object.persisted? && can?(:edit, f.object) %>
      <span class="icon icon-move handle"></span>
      <%= f.hidden_field :id %>
    <% end %>
  </td>
  
  <td class="name">    
    <%= f.text_field :name, class: 'form-control' %>    
  </td>
  
  <td class="presentation">
    <%= f.text_field :presentation, class: 'form-control' %>
  </td>
  
  <td class="price">
    <%= f.text_field :price, class: 'form-control' %>
  </td>

  <td class="price-per-unit">
    <%= f.check_box :price_per_unit, class: 'form-control' %>
  </td>

  <td class="actions actions-1">
    <% if f.object.persisted? && can?(:destroy, f.object) %>
      <%= link_to_delete f.object, no_text: true %>
      <%= link_to_edit f.object, no_text: true %>
    <% end %>
  </td>

</tr>

app/views/spree/admin/product_customization_options/_product_customization_option_fields.html.erb
<tr class="product_customization_option fields" id="spree_<%= dom_id(f.object) %>" data-hook="product_customization_option">
  <td class="move-handle">
    <% if f.object.persisted? && can?(:edit, f.object) %>
      <span class="icon icon-move handle"></span>
      <%= f.hidden_field :id %>
    <% end %>
  </td>
  <td class='customization_option_name'>
    <%= f.text_field :customization_option_name, class: 'autocomplete form-control' %>
  </td>
  <td class='name'>
    <%= f.text_field :name, class: 'form-control' %>
  </td>
   <td class='required'>
    <%= f.check_box :required, class: 'form-control' %>
  </td>
  <td class="actions actions-1">
    <% if f.object.persisted? && can?(:destroy, f.object) %>
      <%= link_to_delete f.object, no_text: true %>
      <%= link_to_edit f.object, no_text: true %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/product_customization_options/_product_customization_option_value_fields.html.erb
<tr class="product_customization_option_value fields" id="spree_<%= dom_id(f.object) %>" data-hook="product_customization_option_value">

  <td class="move-handle">
    <% if f.object.persisted? && can?(:edit, f.object) %>
      <span class="icon icon-move handle"></span>
      <%= f.hidden_field :id %>
    <% end %>
  </td>
  
  <td class="name">    
    <%= f.text_field :name, class: 'form-control' %>    
  </td>
  
  <td class="presentation">
    <%= f.text_field :presentation, class: 'form-control' %>
  </td>
  
  <td class="price">
    <%= f.text_field :price, class: 'form-control' %>
  </td>

  <td class="price-per-unit">
    <%= f.check_box :price_per_unit, class: 'form-control' %>
  </td>

  <td class="actions actions-1">
    <% if f.object.persisted? && can?(:destroy, f.object) %>
      <%= link_to_delete f.object, no_text: true %>
    <% end %>
  </td>

</tr>

app/views/spree/admin/product_customization_options/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::ProductCustomizationOption.model_name.human) %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @product_customization_option } %>

<%= form_for [:admin, @product, @product_customization_option] do |f| %>
	<div data-hook="admin_product_customization_option_form" class="row">
	  <div class="col-md-6">
	    <%= f.field_container :name, class: ['form-group'] do %>
	      <%= f.label :name, Spree.t(:display) %> <span class="required">*</span>
	      <%= f.text_field :name, :class => 'form-control' %>
	      <%= f.error_message_on :name %>
	    <% end %>
	  </div>
	  <div class="col-md-6">
	    <%= f.field_container :required, class: ['form-group'] do %>
	      <%= f.label :required, Spree.t(:required) %> <span class="required">*</span>
	      <%= f.check_box :required, :class => 'form-control' %>
	      <%= f.error_message_on :required %>
	    <% end %>
	  </div>
	</div>



	<!-- check the customization option types, display possible customization option values accordningly -->
	<div id="customization_option_values_form" class="panel panel-default" data-hook>
		<div class="panel-heading">
		<%= @product_customization_option.name %> Values
		</div>

		<div class="panel-body">
			<table class="table sortable" data-hook data-sortable-link="<%= update_positions_admin_product_product_customization_option_product_customization_option_values_url({product_customization_option_id: @product_customization_option.id}) %>">
	      <thead>
	        <tr data-hook="product_customization_option_values_header">
	          <th colspan="2">Backend Name (Shown on orders)</th>
	          <th>Display Name (Shown on website)</th>
	          <th><%= Spree.t(:price) %></th>
	          <th><%= Spree.t(:price_per_unit) %></th>
	          <th class="actions"></th>
	        </tr>
	      </thead>
	      <tbody id="product_customization_option_values" data-hook>
	        <%= f.fields_for :product_customization_option_values do |pcov_form| %>
	          <%= render 'product_customization_option_value_fields', f: pcov_form %>
	        <% end %>
	      </tbody>
	    </table>

    <% if false %>
			<% case @product_customization_option.customization_option.name
			  when "Message" %>
				<%= render 'message_customization_values', :f => builder %>
				<% when "Clipart" %>
				Clipart
				<% when "Image Upload" %>
				Image
				<% when "Imprint Color" %>
				Imprint Color Options
			<% end %>
		<% end %>

			<div class="form-actions text-center" data-hook="buttons">
		    <%= button_link_to(Spree.t(:add_customization_option_value), "javascript:;", { icon: 'add', :'data-target' => "tbody#product_customization_option_values", class: 'spree_add_fields' }) %>
		  </div>
    </div>

	</div>

  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

<%= javascript_tag do %>
  var product_customization_option = <%= raw(@product_customization_option.to_json) %>;
  $('#product_product_customization_option').on('keydown', 'input.autocomplete', function() {
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({source: product_customization_option});
      $(this).focus();
    }
  });
<% end %>

app/views/spree/admin/product_customization_options/index.html.erb
<%= render 'spree/admin/shared/product_tabs', current: :customization %>
<%= render 'spree/admin/shared/error_messages', target: @product %>

<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:add_customization_options), "javascript:;", { icon: 'add', :'data-target' => "tbody#product_customization_options", class: 'btn-success spree_add_fields' }) %>
  <span class="js-new-ptype-link"><%= button_link_to Spree.t(:select_from_prototype), available_admin_prototypes_url, { icon: 'properties', remote: true, 'data-update' => 'prototypes', class: 'btn-default' } %></span>
<% end if can? :create, Spree::ProductProperty %>

<%= form_for @product, url: spree.admin_product_url(@product), method: :put do |f| %>
  <fieldset>
    <div id="prototypes" data-hook></div>

    <table class="table sortable" data-hook data-sortable-link="<%= update_positions_admin_product_product_customization_options_url %>">
      <thead>
        <tr data-hook="product_customization_options_header">
          <th colspan="2"><%= Spree.t(:customization_option) %></th>
          <th><%= Spree.t(:display_name) %></th>
          <th><%= Spree.t(:required) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="product_customization_options" data-hook>
        <%= f.fields_for :product_customization_options do |pco_form| %>
          <%= render 'product_customization_option_fields', f: pco_form %>
        <% end %>
      </tbody>
    </table>

    <%= render('spree/admin/shared/edit_resource_links') if can? :update, Spree::ProductProperty %>

    <%= hidden_field_tag 'clear_product_customization_options', 'true' %>
  </fieldset>
<% end %>

<%= javascript_tag do %>
  var customization_options = <%= raw(@customization_options.to_json) %>;
  $('#product_customization_options').on('keydown', 'input.autocomplete', function() {
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({source: customization_options});
      $(this).focus();
    }
  });
<% end %>

app/views/spree/admin/product_customization_options/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @customization_option } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_customization_option) %>
<% end %>

<%= form_for [:admin, @customization_option] do |f| %>
  <fieldset data-hook="new_property">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-actions">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/shared/_product_tabs.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:products), admin_products_path %> /
  <%= @product.name %>
<% end %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" data-hook="admin_product_tabs">
    <%= content_tag :li, class: ('active' if current == :details) do %>
      <%= link_to_with_icon 'edit', Spree.t(:details), edit_admin_product_url(@product) %>
    <% end if can?(:admin, Spree::Product) %>
    <%= content_tag :li, class: ('active' if current == :images) do %>
      <%= link_to_with_icon 'picture', Spree.t(:images), spree.admin_product_images_url(@product) %>
    <% end if can?(:admin, Spree::Image) %>
    <%= content_tag :li, class: ('active' if current == :variants) do %>
      <%= link_to_with_icon 'th-large', Spree.t(:variants),  spree.admin_product_variants_url(@product) %>
    <% end if can?(:admin, Spree::Variant) %>
    <%= content_tag :li, class: ('active' if current == :properties) do %>
      <%= link_to_with_icon 'list-alt', Spree.t(:properties), spree.admin_product_product_properties_url(@product) %>
    <% end if can?(:admin, Spree::ProductProperty) %>
    <%= content_tag :li, class: ('active' if current == :stock) do %>
      <%= link_to_with_icon 'home', Spree.t(:stock), stock_admin_product_url(@product) %>
    <% end if can?(:stock, Spree::Product) %>
    <%= content_tag :li, class: ('active' if current == :customization) do %>
      <%= link_to_with_icon 'edit', Spree.t(:customization), spree.admin_product_product_customization_options_url(@product) %>
    <% end if can?(:admin, Spree::Product) %>
  </ul>
<% end %>

app/views/spree/admin/shared/sub_menu/_product.html.erb
<ul id="sidebar-product" class="collapse nav nav-pills nav-stacked" data-hook="admin_product_sub_tabs">
  <%= tab *Spree::BackendConfiguration::PRODUCT_TABS %>
  <%= tab :option_types, :match_path => '/option_types' %>
  <%= tab :properties %>
  <%= tab :prototypes %>
  <%= tab :taxonomies %>
  <%= tab :taxons %>
  <%= tab :customization_options %>
</ul>